# Use the official Node.js image
FROM node:24.0.2

# Create and change to the app directory
WORKDIR /workspace/simple-web-app/simple-web-app/app.js

# Copy application dependency manifests to the container image
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Run the web service on container startup
CMD ["node", "app.js"]
